### ISSUE TITLE
/me command for TenThings

### ISSUE THREAD

**Issue by icedwater** [FlandersBurger/resume#2]
Private message for personal stats where available, and announce to channel otherwise.

Easier to /me than to /stats > Player Stats > My Stats.

**Comment by FlandersBurger** [comment]
/Me is implemented, however it doesn't check for personal chats yet, I got distracted with checking whether chats existed at all and implemented something to delete non-existing chats, haha.

**Comment by icedwater** [comment]
I guess this is done :)
